name: Comment before Vercel
on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message
        run: |
          echo "👋 Bonjour depuis GitHub Actions !"
          echo "Repo: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"